# Generated by Django 5.2.1 on 2025-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindTurbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('installation_date', models.DateField()),
                ('capacity_kw', models.FloatField(help_text='Puterea instalată în kW')),
            ],
        ),
    ]
