# Generated by Django 5.2.1 on 2025-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbine',
            name='instant_output_kw',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='windturbine',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windturbine',
            name='maintenance_done',
            field=models.BooleanField(default=False),
        ),
    ]
